package frc.robot.controller_map;

import frc.robot.controller_map.XboxPov;

public class XboxMap {

    //BUTTONS
    public final static int BUTTON_A = 1;
    public final static int BUTTON_B = 2;
    public final static int BUTTON_X = 3;
    public final static int BUTTON_Y = 4;
    public final static int BUTTON_LEFT_BUMPER = 5;
    public final static int BUTTON_RIGHT_BUMPER = 6;
    public final static int BUTTON_START = 7;
    public final static int BUTTON_BACK = 8;
    public final static int BUTTON_LEFT_STICK = 9;
    public final static int BUTTON_RIGHT_STICK = 10;

    public final static int AXIS_LEFT_STICK_X = 1;
    public final static int AXIS_LEFT_STICK_Y = 2;
    public final static int AXIS_RIGHT_STICK_X = 3;
    public final static int AXIS_RIGHT_STICK_Y = 4;
    public final static int AXIS_LEFT_TRIGGER = 5;
    public final static int AXIS_RIGHT_TRIGGER = 6;

    void getPOV() {
        XboxController xbox;
        
    }
} 